### ISSUE TITLE
Getting 403 error

### ISSUE THREAD

**Issue by MarcelloTheArcane** [diraimondo/gmusicproxy#106]
I can't load any songs using gmusicproxy since a few days ago (getting the following **403 error**)

I think still have access to Google Music (it works elsewhere), is this an Google API change or something else?

Here's the error log:

```
Searching for song with query: [song query]
Selected song: [song name]
Streaming song with id '[song id]': [song name]
----------------------------------------
Exception happened during processing of request from ('[my ip]', [port])
Traceback (most recent call last):
  File "/usr/lib64/python2.7/SocketServer.py", line 596, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib64/python2.7/SocketServer.py", line 331, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib64/python2.7/SocketServer.py", line 652, in __init__
    self.handle()
  File "/usr/lib64/python2.7/BaseHTTPServer.py", line 340, in handle
    self.handle_one_request()
  File "/home/[user]/gmusicproxy/GMusicProxy", line 724, in handle_one_request
    BaseHTTPRequestHandler.handle_one_request(self)
  File "/usr/lib64/python2.7/BaseHTTPServer.py", line 328, in handle_one_request
    method()
  File "/home/[user]/gmusicproxy/GMusicProxy", line 164, in do_GET
    self._get_song(result)
  File "/home/[user]/gmusicproxy/GMusicProxy", line 326, in _get_song
    url = self._robust_retry(lambda: api.get_stream_url(song_id=id))
  File "<decorator-gen-142>", line 2, in _robust_retry
  File "/usr/lib/python2.7/site-packages/gmusicapi/utils/utils.py", line 387, in retry_wrapper
    return f(*args, **kwargs)
  File "/home/[user]/gmusicproxy/GMusicProxy", line 720, in _robust_retry
    return func()
  File "/home/[user]/gmusicproxy/GMusicProxy", line 326, in <lambda>
    url = self._robust_retry(lambda: api.get_stream_url(song_id=id))
  File "<decorator-gen-102>", line 2, in get_stream_url
  File "/usr/lib/python2.7/site-packages/gmusicapi/utils/utils.py", line 293, in wrapper
    return function(*args, **kw)
  File "/usr/lib/python2.7/site-packages/gmusicapi/clients/mobileclient.py", line 388, in get_stream_url
    return self._make_call(mobileclient.GetStreamUrl, song_id, device_id, quality)
  File "/usr/lib/python2.7/site-packages/gmusicapi/clients/shared.py", line 84, in _make_call
    return protocol.perform(self.session, self.validate, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/gmusicapi/protocol/shared.py", line 226, in perform
    raise CallFailure(err_msg, call_name)
CallFailure: GetStreamUrl: 403 Client Error: Forbidden for url: https://mclients.googleapis.com/music/mplay?opt=hi&mjck=[song id]&pt=e&slt=[some id]&tier=aa&sig=[another id]&hl=en_US&dv=0&net=mob
(requests kwargs: {u'url': u'https://mclients.googleapis.com/music/mplay', u'headers': {u'X-Device-ID': u'[device id]', u'Authorization': u'<omitted>'}, u'allow_redirects': False, u'params': {u'opt': u'hi', u'mjck': u'[song id]', u'pt': u'e', u'slt': '[some id]', u'tier': u'aa', u'sig': '[another id]', u'hl': u'en_US', u'dv': 0, u'net': u'mob'}, u'method': u'GET'})
(response was: u'<HTML>\n<HEAD>\n<TITLE>Forbidden</TITLE>\n</HEAD>\n<BODY BGCOLOR="#FFFFFF" TEXT="#000000">\n<H1>Forbidden</H1>\n<H2>Error 403</H2>\n</BODY>\n</HTML>\n')
----------------------------------------
```

**Comment by MarcelloTheArcane** [comment]
Related issue on gmusicapi: https://github.com/simon-weber/gmusicapi/issues/149

I've tried it on two IDs (as they suggest changing), neither works.

**Comment by MarcelloTheArcane** [comment]
Okay, I've solved this now.

Here's what I did, if anyone else has this issue...

1. Log onto the server running `gmusicproxy`
2. run `python`
3. run the following code:
```python
import gmusicapi
email = [your email]
password = [your password/app-specific password]
Mobileclient = gmusicapi.clients.Mobileclient(debug_logging=True, validate=True, verify_ssl=True)
Mobileclient.login(email, password, '[faulty android id]', locale=u'en_US')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/gmusicapi/clients/mobileclient.py", line 143, in login
    self.android_id = self._validate_device_id(device_id, is_mac=is_mac)
  File "/usr/lib/python2.7/site-packages/gmusicapi/clients/mobileclient.py", line 58, in _validate_device_id
    raise InvalidDeviceId('Invalid device_id %s.' % device_id, devices)
gmusicapi.exceptions.InvalidDeviceId: Invalid device_id [faulty android id].Your valid device IDs are:
* [an id]
* [another id]
* [maybe another id]
```

I used the longest one of the 3 it gave me.

4. create/modify your [gmusicproxy config file](http://gmusicproxy.net/#gmusicproxy-google-play-music-proxy-usage-config-file) to include the line:
`device-id = [the longer id, or whatever works]`

**Comment by theowen** [comment]
This worked but I had to use the shorter ID (and deactivate some)

**Comment by MarcelloTheArcane** [comment]
@theowen any ideas why it suddenly breaks?

**Comment by theowen** [comment]
403 means forbidden, you need to predend to be a real device I guess
