### ISSUE TITLE
get_song - bad request

### ISSUE THREAD

**Issue by kicumkicum** [diraimondo/gmusicproxy#11]
I can not listen any music. When I use http://localhost:9999/get_song?id=Txjwctvqcxcin4olnkeurhcndpu 
I get 

127.0.0.1 - - [21/Jun/2014 17:23:41] "GET /get_song?id=Txjwctvqcxcin4olnkeurhcndpu HTTP/1.1" 200 -

Exception happened during processing of request from ('127.0.0.1', 60587)
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 295, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 321, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 649, in __init__
    self.handle()
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 340, in handle
    self.handle_one_request()
  File "/usr/local/bin/GMusicProxy", line 410, in handle_one_request
    BaseHTTPServer.BaseHTTPRequestHandler.handle_one_request(self)
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 328, in handle_one_request
    method()
  File "/usr/local/bin/GMusicProxy", line 39, in do_GET
    self._get_song(id=params['id'][0])
  File "/usr/local/bin/GMusicProxy", line 165, in _get_song
    info = self._robust_retry(lambda:api.get_track_info(store_track_id=id))
  File "<string>", line 2, in _robust_retry
  File "/usr/local/lib/python2.7/dist-packages/gmusicapi/utils/utils.py", line 382, in retry_wrapper
    return f(*args, **kwargs)
  File "/usr/local/bin/GMusicProxy", line 406, in _robust_retry
    return func()
  File "/usr/local/bin/GMusicProxy", line 165, in <lambda>
    info = self._robust_retry(lambda:api.get_track_info(store_track_id=id))
  File "<string>", line 2, in get_track_info
  File "/usr/local/lib/python2.7/dist-packages/gmusicapi/utils/utils.py", line 288, in wrapper
    return function(*args, **kw)
  File "/usr/local/lib/python2.7/dist-packages/gmusicapi/clients/mobileclient.py", line 1012, in get_track_info
    return self._make_call(mobileclient.GetStoreTrack, store_track_id)
  File "/usr/local/lib/python2.7/dist-packages/gmusicapi/clients/shared.py", line 80, in _make_call
    return protocol.perform(self.session, self.validate, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/gmusicapi/protocol/shared.py", line 225, in perform
    raise CallFailure(err_msg, call_name)
CallFailure: GetStoreTrack: 400 Client Error: Bad Request
(requests kwargs: {'url': 'https://www.googleapis.com/sj/v1.5/fetchtrack', 'headers': {'Content-Type': 'application/json', 'Authorization': '<omitted>'}, 'params': {'alt': 'json', 'nid': 'Txjwctvqcxcin4olnkeurhcndpu'}, 'method': 'GET'})
(response was: '{\n "error": {\n  "errors": [\n   {\n    "domain": "global",\n    "reason": "badRequest",\n    "message": "Bad Request"\n   }\n  ],\n  "code": 400,\n  "message": "Bad Request"\n }\n}\n')

**Comment by diraimondo** [comment]
Can you check if last PR fix this?

**Comment by diraimondo** [comment]
I had no feedback on the persistence of the problem. 

Feel free to reopen the report if the bug is still present.

**Comment by diraimondo** [comment]
Now I focused this old problem. Trying to fix it...
