### ISSUE TITLE
Is it still working?

### ISSUE THREAD

**Issue by joralm** [diraimondo/gmusicproxy#24]
after 2 atemps to install on debian and on ubunto, same results. can anyone give some help?

take a look at this log:

192.168.0.113 - - [02/Mar/2015 20:19:06] "GET /get_song?id=T7wmefscihezccr3nosm4ybjeyi HTTP/1.1" 200 -
----------------------------------------
Exception happened during processing of request from ('192.168.0.113', 33326)
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 295, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 321, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 649, in __init__
    self.handle()
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 340, in handle
    self.handle_one_request()
  File "/usr/local/bin/GMusicProxy", line 449, in handle_one_request
    BaseHTTPServer.BaseHTTPRequestHandler.handle_one_request(self)
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 328, in handle_one_request
    method()
  File "/usr/local/bin/GMusicProxy", line 42, in do_GET
    self._get_song(id=params['id'][0])
  File "/usr/local/bin/GMusicProxy", line 170, in _get_song
    info = self._robust_retry(lambda:api.get_track_info(store_track_id=id))
  File "<string>", line 2, in _robust_retry
  File "/usr/local/lib/python2.7/dist-packages/gmusicapi/utils/utils.py", line 382, in retry_wrapper
    return f(*args, **kwargs)
  File "/usr/local/bin/GMusicProxy", line 445, in _robust_retry
    return func()
  File "/usr/local/bin/GMusicProxy", line 170, in <lambda>
    info = self._robust_retry(lambda:api.get_track_info(store_track_id=id))
  File "<string>", line 2, in get_track_info
  File "/usr/local/lib/python2.7/dist-packages/gmusicapi/utils/utils.py", line 288, in wrapper
    return function(*args, **kw)
  File "/usr/local/lib/python2.7/dist-packages/gmusicapi/clients/mobileclient.py", line 1012, in get_track_info
    return self._make_call(mobileclient.GetStoreTrack, store_track_id)
  File "/usr/local/lib/python2.7/dist-packages/gmusicapi/clients/shared.py", line 80, in _make_call
    return protocol.perform(self.session, self.validate, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/gmusicapi/protocol/shared.py", line 225, in perform
    raise CallFailure(err_msg, call_name)
CallFailure: GetStoreTrack: 400 Client Error: Bad Request
(requests kwargs: {'url': 'https://www.googleapis.com/sj/v1.5/fetchtrack', 'headers': {'Content-Type': 'application/json', 'Authorization': '<omitted>'}, 'params': {'alt': 'json', 'nid': 'T7wmefscihezccr3nosm4ybjeyi'}, 'method': 'GET'})
(response was: '{\n "error": {\n  "errors": [\n   {\n    "domain": "global",\n    "reason": "badRequest",\n    "message": "Bad Request"\n   }\n  ],\n  "code": 400,\n  "message": "Bad Request"\n }\n}\n')

**Comment by joralm** [comment]
IT WORKS!!! I think we must have all access! And i was trying to play music i had upload and it did´t work!

**Comment by diraimondo** [comment]
Nave you tested latest commit (master) with uploaded tracks?

Mario

Il giorno mar 3 mar 2015 00:44 joralm <notifications@github.com> ha scritto:
