### ISSUE TITLE
Unable to install dependencies

### ISSUE THREAD

**Issue by mrThe** [diraimondo/gmusicproxy#33]
Hi there. I'm trying to install gmusicproxy on ubuntu(with vagrant) and get this errors:

```
vagrant@vagrant-ubuntu:~/gmusicproxy$ sudo pip install -r requirements.txt
Obtaining file:///home/vagrant/gmusicproxy (from -r requirements.txt (line 3))
  Running setup.py egg_info for package from file:///home/vagrant/gmusicproxy

Downloading/unpacking gmusicapi>=6.0.0 (from gmusicproxy==1.0.2->-r requirements.txt (line 3))
  Running setup.py egg_info for package gmusicapi

    warning: no previously-included files matching '_local_*.py' found anywhere in distribution
Downloading/unpacking netifaces>=0.10.4 (from gmusicproxy==1.0.2->-r requirements.txt (line 3))
  Running setup.py egg_info for package netifaces

Downloading/unpacking pyxdg>=0.25 (from gmusicproxy==1.0.2->-r requirements.txt (line 3))
  Running setup.py egg_info for package pyxdg

Downloading/unpacking eyed3>=0.7.8 (from gmusicproxy==1.0.2->-r requirements.txt (line 3))
  Running setup.py egg_info for package eyed3
    warning: no previously-included files matching '*' found under directory 'docs/_build'
Downloading/unpacking python-daemon>=2.0.5 (from gmusicproxy==1.0.2->-r requirements.txt (line 3))
  Running setup.py egg_info for package python-daemon

    Traceback (most recent call last):
      File "<string>", line 14, in <module>
      File "/home/vagrant/gmusicproxy/build/python-daemon/setup.py", line 97, in <module>
        "Topic :: Software Development :: Libraries :: Python Modules",
      File "/usr/lib/python2.7/distutils/core.py", line 152, in setup
        dist.run_commands()
      File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "version.py", line 500, in run
        self.run_command(command_name)
      File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "version.py", line 538, in run
        version_info = generate_version_info_from_changelog(self.changelog_path)
      File "version.py", line 414, in generate_version_info_from_changelog
        versions_all_json = changelog_to_version_info_collection(infile)
      File "version.py", line 369, in changelog_to_version_info_collection
        import docutils.core
      File "/home/vagrant/gmusicproxy/build/python-daemon/docutils-0.12-py2.7.egg/docutils/core.py", line 20, in <module>
        from docutils import frontend, io, utils, readers, writers
      File "/home/vagrant/gmusicproxy/build/python-daemon/docutils-0.12-py2.7.egg/docutils/frontend.py", line 41, in <module>
        import docutils.utils
      File "/home/vagrant/gmusicproxy/build/python-daemon/docutils-0.12-py2.7.egg/docutils/utils/__init__.py", line 20, in <module>
        import docutils.io
      File "/home/vagrant/gmusicproxy/build/python-daemon/docutils-0.12-py2.7.egg/docutils/io.py", line 18, in <module>
        from docutils.utils.error_reporting import locale_encoding, ErrorString, ErrorOutput
      File "/home/vagrant/gmusicproxy/build/python-daemon/docutils-0.12-py2.7.egg/docutils/utils/error_reporting.py", line 47, in <module>
        locale_encoding = locale.getlocale()[1] or locale.getdefaultlocale()[1]
      File "/usr/lib/python2.7/locale.py", line 503, in getdefaultlocale
        return _parse_localename(localename)
      File "/usr/lib/python2.7/locale.py", line 435, in _parse_localename
        raise ValueError, 'unknown locale: %s' % localename
    ValueError: unknown locale: UTF-8
    Complete output from command python setup.py egg_info:
    running egg_info

writing requirements to pip-egg-info/python_daemon.egg-info/requires.txt

writing pip-egg-info/python_daemon.egg-info/PKG-INFO

writing top-level names to pip-egg-info/python_daemon.egg-info/top_level.txt

writing dependency_links to pip-egg-info/python_daemon.egg-info/dependency_links.txt

warning: manifest_maker: standard file '-c' not found



reading manifest file 'pip-egg-info/python_daemon.egg-info/SOURCES.txt'

reading manifest template 'MANIFEST.in'

writing manifest file 'pip-egg-info/python_daemon.egg-info/SOURCES.txt'

running write_version_info

Traceback (most recent call last):

  File "<string>", line 14, in <module>

  File "/home/vagrant/gmusicproxy/build/python-daemon/setup.py", line 97, in <module>

    "Topic :: Software Development :: Libraries :: Python Modules",

  File "/usr/lib/python2.7/distutils/core.py", line 152, in setup

    dist.run_commands()

  File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands

    self.run_command(cmd)

  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command

    cmd_obj.run()

  File "version.py", line 500, in run

    self.run_command(command_name)

  File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command

    self.distribution.run_command(command)

  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command

    cmd_obj.run()

  File "version.py", line 538, in run

    version_info = generate_version_info_from_changelog(self.changelog_path)

  File "version.py", line 414, in generate_version_info_from_changelog

    versions_all_json = changelog_to_version_info_collection(infile)

  File "version.py", line 369, in changelog_to_version_info_collection

    import docutils.core

  File "/home/vagrant/gmusicproxy/build/python-daemon/docutils-0.12-py2.7.egg/docutils/core.py", line 20, in <module>

    from docutils import frontend, io, utils, readers, writers

  File "/home/vagrant/gmusicproxy/build/python-daemon/docutils-0.12-py2.7.egg/docutils/frontend.py", line 41, in <module>

    import docutils.utils

  File "/home/vagrant/gmusicproxy/build/python-daemon/docutils-0.12-py2.7.egg/docutils/utils/__init__.py", line 20, in <module>

    import docutils.io

  File "/home/vagrant/gmusicproxy/build/python-daemon/docutils-0.12-py2.7.egg/docutils/io.py", line 18, in <module>

    from docutils.utils.error_reporting import locale_encoding, ErrorString, ErrorOutput

  File "/home/vagrant/gmusicproxy/build/python-daemon/docutils-0.12-py2.7.egg/docutils/utils/error_reporting.py", line 47, in <module>

    locale_encoding = locale.getlocale()[1] or locale.getdefaultlocale()[1]

  File "/usr/lib/python2.7/locale.py", line 503, in getdefaultlocale

    return _parse_localename(localename)

  File "/usr/lib/python2.7/locale.py", line 435, in _parse_localename

    raise ValueError, 'unknown locale: %s' % localename

ValueError: unknown locale: UTF-8

----------------------------------------
Command python setup.py egg_info failed with error code 1
Storing complete log in /home/vagrant/.pip/pip.log
```

```
$ cat /home/vagrant/.pip/pip.log
------------------------------------------------------------
/usr/bin/pip run on Mon Aug  3 11:16:42 2015
Obtaining file:///home/vagrant/gmusicproxy (from -r requirements.txt (line 3))
  Running setup.py egg_info for package from file:///home/vagrant/gmusicproxy
    running egg_info
    writing requirements to gmusicproxy.egg-info/requires.txt
    writing gmusicproxy.egg-info/PKG-INFO
    writing top-level names to gmusicproxy.egg-info/top_level.txt
    writing dependency_links to gmusicproxy.egg-info/dependency_links.txt
    warning: manifest_maker: standard file '-c' not found

    reading manifest file 'gmusicproxy.egg-info/SOURCES.txt'
    writing manifest file 'gmusicproxy.egg-info/SOURCES.txt'
Downloading/unpacking gmusicapi>=6.0.0 (from gmusicproxy==1.0.2->-r requirements.txt (line 3))
  Running setup.py egg_info for package gmusicapi
    running egg_info
    writing requirements to pip-egg-info/gmusicapi.egg-info/requires.txt
    writing pip-egg-info/gmusicapi.egg-info/PKG-INFO
    writing top-level names to pip-egg-info/gmusicapi.egg-info/top_level.txt
    writing dependency_links to pip-egg-info/gmusicapi.egg-info/dependency_links.txt
    warning: manifest_maker: standard file '-c' not found

    reading manifest file 'pip-egg-info/gmusicapi.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    warning: no previously-included files matching '_local_*.py' found anywhere in distribution
    writing manifest file 'pip-egg-info/gmusicapi.egg-info/SOURCES.txt'
  Source in ./build/gmusicapi has version 6.0.0, which satisfies requirement gmusicapi>=6.0.0 (from gmusicproxy==1.0.2->-r requirements.txt (line 3))
Downloading/unpacking netifaces>=0.10.4 (from gmusicproxy==1.0.2->-r requirements.txt (line 3))
  Running setup.py egg_info for package netifaces
    running egg_info
    writing pip-egg-info/netifaces.egg-info/PKG-INFO
    writing top-level names to pip-egg-info/netifaces.egg-info/top_level.txt
    writing dependency_links to pip-egg-info/netifaces.egg-info/dependency_links.txt
    warning: manifest_maker: standard file '-c' not found

    reading manifest file 'pip-egg-info/netifaces.egg-info/SOURCES.txt'
    writing manifest file 'pip-egg-info/netifaces.egg-info/SOURCES.txt'
  Source in ./build/netifaces has version 0.10.4, which satisfies requirement netifaces>=0.10.4 (from gmusicproxy==1.0.2->-r requirements.txt (line 3))
Downloading/unpacking pyxdg>=0.25 (from gmusicproxy==1.0.2->-r requirements.txt (line 3))
  Running setup.py egg_info for package pyxdg
    running egg_info
    writing pip-egg-info/pyxdg.egg-info/PKG-INFO
    writing top-level names to pip-egg-info/pyxdg.egg-info/top_level.txt
    writing dependency_links to pip-egg-info/pyxdg.egg-info/dependency_links.txt
    warning: manifest_maker: standard file '-c' not found

    reading manifest file 'pip-egg-info/pyxdg.egg-info/SOURCES.txt'
    writing manifest file 'pip-egg-info/pyxdg.egg-info/SOURCES.txt'
  Source in ./build/pyxdg has version 0.25, which satisfies requirement pyxdg>=0.25 (from gmusicproxy==1.0.2->-r requirements.txt (line 3))
Downloading/unpacking eyed3>=0.7.8 (from gmusicproxy==1.0.2->-r requirements.txt (line 3))
  Running setup.py egg_info for package eyed3
    running egg_info
    writing pip-egg-info/eyeD3.egg-info/PKG-INFO
    writing top-level names to pip-egg-info/eyeD3.egg-info/top_level.txt
    writing dependency_links to pip-egg-info/eyeD3.egg-info/dependency_links.txt
    reading manifest file 'pip-egg-info/eyeD3.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    warning: no previously-included files matching '*' found under directory 'docs/_build'
    writing manifest file 'pip-egg-info/eyeD3.egg-info/SOURCES.txt'
  Source in ./build/eyed3 has version 0.7.8, which satisfies requirement eyed3>=0.7.8 (from gmusicproxy==1.0.2->-r requirements.txt (line 3))
Downloading/unpacking python-daemon>=2.0.5 (from gmusicproxy==1.0.2->-r requirements.txt (line 3))
  Running setup.py egg_info for package python-daemon
    running egg_info
    writing requirements to pip-egg-info/python_daemon.egg-info/requires.txt
    writing pip-egg-info/python_daemon.egg-info/PKG-INFO
    writing top-level names to pip-egg-info/python_daemon.egg-info/top_level.txt
    writing dependency_links to pip-egg-info/python_daemon.egg-info/dependency_links.txt
    warning: manifest_maker: standard file '-c' not found

    reading manifest file 'pip-egg-info/python_daemon.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    writing manifest file 'pip-egg-info/python_daemon.egg-info/SOURCES.txt'
    running write_version_info
    Traceback (most recent call last):
      File "<string>", line 14, in <module>
      File "/home/vagrant/gmusicproxy/build/python-daemon/setup.py", line 97, in <module>
        "Topic :: Software Development :: Libraries :: Python Modules",
      File "/usr/lib/python2.7/distutils/core.py", line 152, in setup
        dist.run_commands()
      File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "version.py", line 500, in run
        self.run_command(command_name)
      File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "version.py", line 538, in run
        version_info = generate_version_info_from_changelog(self.changelog_path)
      File "version.py", line 414, in generate_version_info_from_changelog
        versions_all_json = changelog_to_version_info_collection(infile)
      File "version.py", line 369, in changelog_to_version_info_collection
        import docutils.core
      File "/home/vagrant/gmusicproxy/build/python-daemon/docutils-0.12-py2.7.egg/docutils/core.py", line 20, in <module>
        from docutils import frontend, io, utils, readers, writers
      File "/home/vagrant/gmusicproxy/build/python-daemon/docutils-0.12-py2.7.egg/docutils/frontend.py", line 41, in <module>
        import docutils.utils
      File "/home/vagrant/gmusicproxy/build/python-daemon/docutils-0.12-py2.7.egg/docutils/utils/__init__.py", line 20, in <module>
        import docutils.io
      File "/home/vagrant/gmusicproxy/build/python-daemon/docutils-0.12-py2.7.egg/docutils/io.py", line 18, in <module>
        from docutils.utils.error_reporting import locale_encoding, ErrorString, ErrorOutput
      File "/home/vagrant/gmusicproxy/build/python-daemon/docutils-0.12-py2.7.egg/docutils/utils/error_reporting.py", line 47, in <module>
        locale_encoding = locale.getlocale()[1] or locale.getdefaultlocale()[1]
      File "/usr/lib/python2.7/locale.py", line 503, in getdefaultlocale
        return _parse_localename(localename)
      File "/usr/lib/python2.7/locale.py", line 435, in _parse_localename
        raise ValueError, 'unknown locale: %s' % localename
    ValueError: unknown locale: UTF-8
    Complete output from command python setup.py egg_info:
    running egg_info

writing requirements to pip-egg-info/python_daemon.egg-info/requires.txt

writing pip-egg-info/python_daemon.egg-info/PKG-INFO

writing top-level names to pip-egg-info/python_daemon.egg-info/top_level.txt

writing dependency_links to pip-egg-info/python_daemon.egg-info/dependency_links.txt

warning: manifest_maker: standard file '-c' not found



reading manifest file 'pip-egg-info/python_daemon.egg-info/SOURCES.txt'

reading manifest template 'MANIFEST.in'

writing manifest file 'pip-egg-info/python_daemon.egg-info/SOURCES.txt'

running write_version_info

Traceback (most recent call last):

  File "<string>", line 14, in <module>

  File "/home/vagrant/gmusicproxy/build/python-daemon/setup.py", line 97, in <module>

    "Topic :: Software Development :: Libraries :: Python Modules",

  File "/usr/lib/python2.7/distutils/core.py", line 152, in setup

    dist.run_commands()

  File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands

    self.run_command(cmd)

  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command

    cmd_obj.run()

  File "version.py", line 500, in run

    self.run_command(command_name)

  File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command

    self.distribution.run_command(command)

  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command

    cmd_obj.run()

  File "version.py", line 538, in run

    version_info = generate_version_info_from_changelog(self.changelog_path)

  File "version.py", line 414, in generate_version_info_from_changelog

    versions_all_json = changelog_to_version_info_collection(infile)

  File "version.py", line 369, in changelog_to_version_info_collection

    import docutils.core

  File "/home/vagrant/gmusicproxy/build/python-daemon/docutils-0.12-py2.7.egg/docutils/core.py", line 20, in <module>

    from docutils import frontend, io, utils, readers, writers

  File "/home/vagrant/gmusicproxy/build/python-daemon/docutils-0.12-py2.7.egg/docutils/frontend.py", line 41, in <module>

    import docutils.utils

  File "/home/vagrant/gmusicproxy/build/python-daemon/docutils-0.12-py2.7.egg/docutils/utils/__init__.py", line 20, in <module>

    import docutils.io

  File "/home/vagrant/gmusicproxy/build/python-daemon/docutils-0.12-py2.7.egg/docutils/io.py", line 18, in <module>

    from docutils.utils.error_reporting import locale_encoding, ErrorString, ErrorOutput

  File "/home/vagrant/gmusicproxy/build/python-daemon/docutils-0.12-py2.7.egg/docutils/utils/error_reporting.py", line 47, in <module>

    locale_encoding = locale.getlocale()[1] or locale.getdefaultlocale()[1]

  File "/usr/lib/python2.7/locale.py", line 503, in getdefaultlocale

    return _parse_localename(localename)

  File "/usr/lib/python2.7/locale.py", line 435, in _parse_localename

    raise ValueError, 'unknown locale: %s' % localename

ValueError: unknown locale: UTF-8

----------------------------------------
Command python setup.py egg_info failed with error code 1
Exception information:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 126, in main
    self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 223, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 980, in prepare_files
    req_to_install.run_egg_info()
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 216, in run_egg_info
    command_desc='python setup.py egg_info')
  File "/usr/lib/python2.7/dist-packages/pip/__init__.py", line 255, in call_subprocess
    % (command_desc, proc.returncode))
InstallationError: Command python setup.py egg_info failed with error code 1

```

```
$ uname -a
Linux vagrant-ubuntu 3.2.0-32-generic #51-Ubuntu SMP Wed Sep 26 21:33:09 UTC 2012 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by diraimondo** [comment]
Your building environment looks broken. You could try to run the command `sudo dpkg-reconfigure locales` and select at least one locale with UTF-8 support. 

Provides the output of `export | grep 'LC_'` before and after the execution of such command.

By the note: this is not a bug of gmusicproxy...

**Comment by mrThe** [comment]
@diraimondo thanks for answer. Really, it's problem with my environment. I fix it by adding
```
export LANGUAGE=en_US.UTF-8
export LANG=en_US.UTF-8
export LC_ALL=en_US.UTF-8
locale-gen en_US.UTF-8
sudo dpkg-reconfigure locales
```

to my  ~/.bashrc. 

Node: it's a dirty hotfix for my vagrant box, don't do that on you host machine.
