### ISSUE TITLE
Exception when Shutting Down proxy

### ISSUE THREAD

**Issue by antondomratchev** [diraimondo/gmusicproxy#36]
Got this exception while trying to shutdown the proxy server. The media player has closed the connection  prior to shutdown.
Trace
```
^CShutting down the proxy...
----------------------------------------
Exception happened during processing of request from ('192.168.1.102', 54126)
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/SocketServer.py", line 295, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/SocketServer.py", line 321, in process_request
    self.finish_request(request, client_address)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/SocketServer.py", line 655, in __init__
    self.handle()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/BaseHTTPServer.py", line 340, in handle
    self.handle_one_request()
  File "/Users/anton/gmusicproxy/GMusicProxy", line 472, in handle_one_request
    BaseHTTPServer.BaseHTTPRequestHandler.handle_one_request(self)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/BaseHTTPServer.py", line 328, in handle_one_request
    method()
  File "/Users/anton/gmusicproxy/GMusicProxy", line 43, in do_GET
    self._get_song(id=params['id'][0])
  File "/Users/anton/gmusicproxy/GMusicProxy", line 210, in _get_song
    self.wfile.write(block)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 328, in write
    self.flush()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 307, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
  File "/Users/anton/gmusicproxy/GMusicProxy", line 499, in signalHandler
    sys.exit()
SystemExit
----------------------------------------
Traceback (most recent call last):
  File "/usr/local/bin/GMusicProxy", line 8, in <module>
    execfile(__file__)
  File "/Users/anton/gmusicproxy/GMusicProxy", line 671, in <module>
    server.serve_forever()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/SocketServer.py", line 236, in serve_forever
    poll_interval)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/SocketServer.py", line 155, in _eintr_retry
    return func(*args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/SocketServer.py", line 459, in fileno
    return self.socket.fileno()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 174, in _dummy
    raise error(EBADF, 'Bad file descriptor')
socket.error: [Errno 9] Bad file descriptor
```

**Comment by diraimondo** [comment]
I remember this kind of errors in my testing breaking the client connection and/or terminating the proxy. I'm not sure about the exact cause of the problem. I ignored the problem because gmusicproxy is supposed to be an always-running-daemon. In the future I will rewrite it using a more robust http server backend. I'm closing this report but feel free to reopen it if the problem break some functionalities.
