### ISSUE TITLE
Permission problems with python-daemon 2.1.0

### ISSUE THREAD

**Issue by onespaceman** [diraimondo/gmusicproxy#40]
```
Google Play Music Proxy 1.0.1 (© Mario Di Raimondo)

Traceback (most recent call last):
  File "/usr/bin/GMusicProxy", line 645, in <module>
    with contextDaemon:
  File "/usr/lib/python2.7/site-packages/daemon/daemon.py", line 394, in __enter__
    self.open()
  File "/usr/lib/python2.7/site-packages/daemon/daemon.py", line 370, in open
    change_process_owner(self.uid, self.gid, self.initgroups)
  File "/usr/lib/python2.7/site-packages/daemon/daemon.py", line 642, in change_process_owner
    raise error
daemon.daemon.DaemonOSEnvironmentError: Unable to change process owner ([Errno 1] Operation not permitted)
```

It runs fine with elevated permissions

Same issue on another project:
https://github.com/ThiefMaster/maildump/issues/17

**Comment by diraimondo** [comment]
Could you confirm that the latest release does it work for you?

**Comment by onespaceman** [comment]
Now getting a syntax error

```
Traceback (most recent call last):
  File "/usr/bin/GMusicProxy", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/home/kirill/git/gmusicproxy/GMusicProxy", line 439
    except socket.error, e:
                       ^
SyntaxError: invalid syntax
```

**Comment by diraimondo** [comment]
You are using python 3 to run GMusicProxy.

**Comment by onespaceman** [comment]
Yep. forgot to specify the python version when creating the virtualenv.

Thanks for the help!
