### ISSUE TITLE
startup issue

### ISSUE THREAD

**Issue by dsmanneke** [diraimondo/gmusicproxy#51]
Google Play Music Proxy 1.0.5 (© Mario Di Raimondo)

Pre-fetching list of songs in collection
Traceback (most recent call last):
  File "GMusicProxy", line 690, in <module>
    server.allSongsCache = api.get_all_songs()
  File "/usr/local/lib/python2.7/dist-packages/gmusicapi/clients/mobileclient.py", line 136, in get_all_songs
    tracks = self._get_all_items(mobileclient.ListTracks, incremental, include_deleted)
  File "/usr/local/lib/python2.7/dist-packages/gmusicapi/clients/mobileclient.py", line 1069, in _get_all_items
    return [s for chunk in generator for s in chunk]
  File "/usr/local/lib/python2.7/dist-packages/gmusicapi/clients/mobileclient.py", line 1082, in _get_all_items_incremental
    **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/gmusicapi/clients/shared.py", line 83, in _make_call
    return protocol.perform(self.session, self.validate, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/gmusicapi/protocol/shared.py", line 210, in perform
    response = session.send(req_kwargs, cls.required_auth)
  File "/usr/local/lib/python2.7/dist-packages/gmusicapi/session.py", line 90, in send
    res = self._send_with_auth(req_kwargs, desired_auth, rsession)
  File "/usr/local/lib/python2.7/dist-packages/gmusicapi/session.py", line 215, in _send_with_auth
    return rsession.request(**req_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests-2.7.0-py2.7.egg/requests/sessions.py", line 465, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests-2.7.0-py2.7.egg/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests-2.7.0-py2.7.egg/requests/adapters.py", line 370, in send
    timeout=timeout
  File "/usr/local/lib/python2.7/dist-packages/requests-2.7.0-py2.7.egg/requests/packages/urllib3/connectionpool.py", line 544, in urlopen
    body=body, headers=headers)
  File "/usr/local/lib/python2.7/dist-packages/requests-2.7.0-py2.7.egg/requests/packages/urllib3/connectionpool.py", line 344, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=conn.timeout)
  File "/usr/local/lib/python2.7/dist-packages/requests-2.7.0-py2.7.egg/requests/packages/urllib3/connectionpool.py", line 314, in _raise_timeout
    if 'timed out' in str(err) or 'did not complete (read)' in str(err):  # Python 2.6
TypeError: __str__ returned non-string (type Error)

**Comment by diraimondo** [comment]
It looks a timeout error in the former network activities. Do you get the same error on each run? Is your network connection stable?
Never seen this kind of problem.

**Comment by dsmanneke** [comment]
it is only on one virtual machine. On a other virtual machine in the same network and operatingsystem, it works.

**Comment by diraimondo** [comment]
It looks a problem of the specific environment running gmusicproxy. I'm closing this report but feel free to reopen it if you collect evidences that this is a bug of the software.
