### ISSUE TITLE
get_all_stations results in Google 500 error

### ISSUE THREAD

**Issue by rsteckler** [diraimondo/gmusicproxy#66]
The call to the proxy:  
```
curl -s 'http://192.168.2.15:8081/get_all_stations'
```

The resulting 500 from Google:
```
192.168.2.108 - - [25/Nov/2016 06:11:17] "GET /get_all_stations HTTP/1.1" 200 -
----------------------------------------
Exception happened during processing of request from ('192.168.2.108', 53134)
----------------------------------------
Getting all stations as M3U list...
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/SocketServer.py", line 596, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/local/lib/python2.7/SocketServer.py", line 331, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/local/lib/python2.7/SocketServer.py", line 652, in __init__
    self.handle()
  File "/usr/local/lib/python2.7/BaseHTTPServer.py", line 340, in handle
    self.handle_one_request()
  File "/usr/local/bin/GMusicProxy", line 509, in handle_one_request
    BaseHTTPServer.BaseHTTPRequestHandler.handle_one_request(self)
  File "/usr/local/lib/python2.7/BaseHTTPServer.py", line 328, in handle_one_request
    method()
  File "/usr/local/bin/GMusicProxy", line 50, in do_GET
    self._get_all_stations(format=params['format'][0] if 'format' in params else 'm3u', separator=params['separator'][0] if 'separator' in params else '|', onlyUrl=params['only_url'][0] if 'only_url' in params else 'no')
  File "/usr/local/bin/GMusicProxy", line 252, in _get_all_stations
    stations = self._robust_retry(lambda:api.get_all_stations())
  File "<decorator-gen-114>", line 2, in _robust_retry
  File "/usr/local/lib/python2.7/site-packages/gmusicapi/utils/utils.py", line 390, in retry_wrapper
    return f(*args, **kwargs)
  File "/usr/local/bin/GMusicProxy", line 505, in _robust_retry
    return func()
  File "/usr/local/bin/GMusicProxy", line 252, in <lambda>
    stations = self._robust_retry(lambda:api.get_all_stations())
  File "/usr/local/lib/python2.7/site-packages/gmusicapi/clients/mobileclient.py", line 760, in get_all_stations
    updated_after=updated_after)
  File "/usr/local/lib/python2.7/site-packages/gmusicapi/clients/mobileclient.py", line 1069, in _get_all_items
    return [s for chunk in generator for s in chunk]
  File "/usr/local/lib/python2.7/site-packages/gmusicapi/clients/mobileclient.py", line 1082, in _get_all_items_incremental
    **kwargs)
  File "/usr/local/lib/python2.7/site-packages/gmusicapi/clients/shared.py", line 83, in _make_call
    return protocol.perform(self.session, self.validate, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/gmusicapi/protocol/shared.py", line 227, in perform
    raise CallFailure(err_msg, call_name)
CallFailure: ListStations: 500 Server Error: Internal Server Error
(requests kwargs: {u'url': u'https://mclients.googleapis.com/sj/v1.11/radio/station', u'headers': {u'Content-Type': u'application/json', u'Authorization': u'<omitted>'}, u'data': '{"max-results": "20000"}', u'method': u'POST', u'params': {u'alt': u'json', u'updated-min': 0, u'include-tracks': u'true'}})
(response was: '{\n "error": {\n  "errors": [\n   {\n    "domain": "global",\n    "reason": "internalError",\n    "message": "Internal Error"\n   }\n  ],\n  "code": 500,\n  "message": "Internal Error"\n }\n}\n')
```

**Comment by diraimondo** [comment]
I'm sorry but I got the same problem with `get_all_stations`. I signaled this problem during this summer to the author of gmusicapi: https://github.com/simon-weber/gmusicapi/issues/485 .
The problem looks related to the internal state of the account (the list of the stations?). Have to renamed some subscribed stations name (as I did)? You could try to delete all stations.

**Comment by rsteckler** [comment]
I'll comment on that thread and close this one since it's an issue in the base library.  Thanks!
