### ISSUE TITLE
fails to run on Windows 10

### ISSUE THREAD

**Issue by mgillespie** [diraimondo/gmusicproxy#76]
> 
Traceback (most recent call last):
  File "GMusicProxy", line 46, in <module>
    import daemon
  File "C:\Python27\lib\site-packages\daemon\__init__.py", line 42, in <module>
    from .daemon import DaemonContext
  File "C:\Python27\lib\site-packages\daemon\daemon.py", line 25, in <module>
    import pwd
ImportError: No module named pwd

> 

The workaround for me, currently, is to comment out the _import daemon_ line.  not sure if there is a better way.  All the correct packages appear to be installed.

**Comment by diraimondo** [comment]
Could you try if last commit fixes your problem?

**Comment by mgillespie** [comment]
Can confirm 1.0.8b1 works correctly on 64bit Win10.
