### ISSUE TITLE
http error 403 'Forbidden'

### ISSUE THREAD

**Issue by discipuloosho** [diraimondo/gmusicproxy#81]
Is this a issue or I have exceeded download limit? My google play music account is premiun, of course, and i have been downloading without problem so far.
Here google response:
`
(response was: u'<HTML>\n<HEAD>\n<TITLE>Forbidden</TITLE>\n</HEAD>\n<BODY BGCOLOR="#FFFFFF" TEXT="#000000">\n<H1>Forbidden</H1>\n<H2>Error 403</H2>\n</BODY>\n</HTML>\n')
`
Here GMusicProxy python exception:
`
CallFailure: GetStreamUrl: 403 Client Error: Forbidden for url: https://mclients.googleapis.com/music/mplay?opt=XXXXXXXXXXXXXX..etc
`
Thanks so much, I will make a donation for your work.

**Comment by discipuloosho** [comment]
https://github.com/diraimondo/gmusicproxy/issues/48

**Comment by diraimondo** [comment]
The kind of errors are usually transient: you should retry in some hours/days.
I've never used any of these problem. Download limit: I don't know if it does exist. Did you streamed (not downloaded....) too many songs...? Can you use the service from Web or Apps? Did you registered too many devices?

**Comment by discipuloosho** [comment]
Download from device without problems, but from GMusicProxy, this exception. I have try with other authorized device-id and doesn't work.  i don't know ..

**Comment by discipuloosho** [comment]
maybe download limit exceeded?

**Comment by diraimondo** [comment]
How many devices are reported using `GMusicProxy -L`? Are they the same in the settings of the web interface? 
Google says you can't remove from the list of the authorized devices more than 4 devices per year and I guess there is also a limit on the maximum number of devices in list...
Maybe you played too much with random ids. I suggest to use ids of real registered devices or the automatic one (linked to the mac address of your network card in order to be constant).

**Comment by discipuloosho** [comment]
Currently, i'm using real authorized device id, but still not working. Device is properly registred in google play music settings and in device works fine, gmusicapi maybe the problem, i don't know. Is rare that in device work fine but with your script not working. I have been downloading satisfactorily until this afternoon after two days downloading.

**Comment by discipuloosho** [comment]
I'm going to wait gmusicapi upgrade ..

**Comment by discipuloosho** [comment]
this is the exception:
`
Streaming song with id 'T6xv6trt34cnnlper6achfbq7xu': Martha Argerich - Schumann: Kinderszenen, Op.15 - 11. Fürchtenmachen
----------------------------------------
Exception happened during processing of request from ('192.168.1.33', 43376)
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 596, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 331, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 652, in __init__
    self.handle()
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 340, in handle
    self.handle_one_request()
  File "/usr/local/lib/python2.7/dist-packages/gmusicproxy-1.0.8b2-py2.7.egg/EGG-INFO/scripts/GMusicProxy", line 678, in handle_one_request
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 328, in handle_one_request
    method()
  File "/usr/local/lib/python2.7/dist-packages/gmusicproxy-1.0.8b2-py2.7.egg/EGG-INFO/scripts/GMusicProxy", line 78, in do_GET
  File "/usr/local/lib/python2.7/dist-packages/gmusicproxy-1.0.8b2-py2.7.egg/EGG-INFO/scripts/GMusicProxy", line 311, in _get_song
  File "<decorator-gen-142>", line 2, in _robust_retry
  File "/usr/local/lib/python2.7/dist-packages/gmusicapi/utils/utils.py", line 387, in retry_wrapper
    return f(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/gmusicproxy-1.0.8b2-py2.7.egg/EGG-INFO/scripts/GMusicProxy", line 674, in _robust_retry
  File "/usr/local/lib/python2.7/dist-packages/gmusicproxy-1.0.8b2-py2.7.egg/EGG-INFO/scripts/GMusicProxy", line 311, in <lambda>
  File "<decorator-gen-102>", line 2, in get_stream_url
  File "/usr/local/lib/python2.7/dist-packages/gmusicapi/utils/utils.py", line 293, in wrapper
    return function(*args, **kw)
  File "/usr/local/lib/python2.7/dist-packages/gmusicapi/clients/mobileclient.py", line 372, in get_stream_url
    return self._make_call(mobileclient.GetStreamUrl, song_id, device_id, quality)
  File "/usr/local/lib/python2.7/dist-packages/gmusicapi/clients/shared.py", line 84, in _make_call
    return protocol.perform(self.session, self.validate, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/gmusicapi/protocol/shared.py", line 226, in perform
    raise CallFailure(err_msg, call_name)
CallFailure: GetStreamUrl: 403 Client Error: Forbidden for url: https://mclients.googleapis.com/music/mplay?opt=hi&mjck=T6xv6trt34cnnlper6achfbq7xu&pt=e&slt=1484433253269&tier=aa&sig=zoTHux9GI4_Lu0mDbp5qcyvVmtA&hl=en_US&dv=0&net=mob
(requests kwargs: {u'url': u'https://mclients.googleapis.com/music/mplay', u'headers': {u'X-Device-ID': '3974422031313760984', u'Authorization': u'<omitted>'}, u'allow_redirects': False, u'params': {u'opt': u'hi', u'mjck': 'T6xv6trt34cnnlper6achfbq7xu', u'pt': u'e', u'slt': '1484433253269', u'tier': u'aa', u'sig': 'zoTHux9GI4_Lu0mDbp5qcyvVmtA', u'hl': u'en_US', u'dv': 0, u'net': u'mob'}, u'method': u'GET'})
(response was: u'<HTML>\n<HEAD>\n<TITLE>Forbidden</TITLE>\n</HEAD>\n<BODY BGCOLOR="#FFFFFF" TEXT="#000000">\n<H1>Forbidden</H1>\n<H2>Error 403</H2>\n</BODY>\n</HTML>\n')
`

**Comment by diraimondo** [comment]
You should wait some days to see if the problem get solved by itself. I don't think this is a problem of gmusicapi: it is working for me and for many other users.
You continue to say you downloaded for two days... could I ask now many songs did you "downloaded" per day? Maybe you discovered some kind of abuse protection of the service...

**Comment by discipuloosho** [comment]
I downloaded 30 gigabytes

**Comment by diraimondo** [comment]
Your are abusing the service. 
GMusicProxy and @simon-weber's  gmusicapi have not been developed for this kind of use.
I'm closing this report.

**Comment by discipuloosho** [comment]
You are nobody to say how I use my account. Thanks anyway.

**Comment by diraimondo** [comment]
You downloaded in one day music for about 218 hours: we are not stupid.

Is it a coincidence that you are wiping all you can from this report?!

**Comment by discipuloosho** [comment]
Bye.
