### ISSUE TITLE
ValueError: year is out of range

### ISSUE THREAD

**Issue by llucps** [diraimondo/gmusicproxy#85]
After updating to the latest 1.0.8 version when I try to play any song that doesn't have a year specified in the ID3 metadata I get this error and jumps to the next song of the playlist.

```
Streaming song with id 'bf4ad2e7-1248-3c94-b8c9-69b8ee1defe7': Yes - 1991-01-01 - Master Of Dream - 206 Give And Take 1_1483611652570.flac
----------------------------------------
Exception happened during processing of request from ('10.42.43.105', 50170)
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/SocketServer.py", line 596, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/SocketServer.py", line 331, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/SocketServer.py", line 652, in __init__
    self.handle()
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/BaseHTTPServer.py", line 340, in handle
    self.handle_one_request()
  File "/Users/*****/gmusicproxy/GMusicProxy", line 714, in handle_one_request
    BaseHTTPServer.BaseHTTPRequestHandler.handle_one_request(self)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/BaseHTTPServer.py", line 328, in handle_one_request
    method()
  File "/Users/*****/gmusicproxy/GMusicProxy", line 78, in do_GET
    self._get_song(id=params['id'][0])
  File "/Users/*****/gmusicproxy/GMusicProxy", line 302, in _get_song
    tags.recording_date = int(info['year'])
  File "/usr/local/lib/python2.7/site-packages/eyed3/id3/tag.py", line 474, in _setRecordingDate
    self._setDate("TDRC", date)
  File "/usr/local/lib/python2.7/site-packages/eyed3/id3/tag.py", line 551, in _setDate
    date = core.Date(date)
  File "/usr/local/lib/python2.7/site-packages/eyed3/core.py", line 282, in __init__
    second if second is not None else 0)
ValueError: year is out of range
```

Can you check whether is my fault or it's a bug?

Thanks.

**Comment by redlulz** [comment]
Oops, that was me. I assumed an empty field would just be omitted.

**Comment by diraimondo** [comment]
@llucps could you confirm the fix?

**Comment by llucps** [comment]
Yes, it's fixed.

Thanks!

**Comment by diraimondo** [comment]
Thanks to @redlulz
