### ISSUE TITLE
ImportError: No module named pathlib

### ISSUE THREAD

**Issue by leosenko** [diraimondo/gmusicproxy#95]
Upon running GMusicProxy, I am getting:
```
Traceback (most recent call last):
  File "/home/leos/.virtualenvs/gmusicproxy/bin/GMusicProxy", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/home/leos/gmusicproxy/GMusicProxy", line 51, in <module>
    import eyed3.id3
  File "/home/leos/.virtualenvs/gmusicproxy/local/lib/python2.7/site-packages/eyed3/__init__.py", line 35, in <module>
    from .utils.log import log                                            # noqa
  File "/home/leos/.virtualenvs/gmusicproxy/local/lib/python2.7/site-packages/eyed3/utils/__init__.py", line 23, in <module>
    import pathlib
ImportError: No module named pathlib
```
If I run python and do import pathlib, it works fine. But if I do workon gmusicproxy and then python and import pathlib, then ImportError: No module named pathlib.

I have never used virtualenv before so it is a bit obscure but I followed the steps outlined in http://gmusicproxy.net/#gmusicproxy-google-play-music-proxy-setup-installation

**Comment by diraimondo** [comment]
What distribution are using?

**Comment by diraimondo** [comment]
gmusicproxy doesn't directly use pathlib library: it is used by eyed3 (a gmusicproxy dependency). If this is a real bug, it should be submitted to eyed3.
